name: Run CI Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    services:
      quickpizza:
        image: ghcr.io/grafana/quickpizza-local:latest
        ports:
          - 3333:3333

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # This exists bc if you destroy all things managed by Terraform and then re-create them... 
      # the project ID will change. This step fetches the right projectID based on the project name.
      - name: Fetch "backend" projectID
        env:
          GRAFANA_API_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          GRAFANA_STACK_ID: ${{ secrets.GRAFANA_STACK_ID }}
        run: |
          ./tools/fetch_gck6_projectID.sh backend

      - name: Set up k6
        uses: grafana/setup-k6-action@v1

      - name: Run backend tests
        uses: grafana/run-k6-action@v1
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          K6_CLOUD_PROJECT_ID: ${{ env.K6_CLOUD_PROJECT_ID }}
          BASE_URL: http://localhost:3333
        with:
          path: |
            ./src/backend/*.ts
          flags: --vus 10 --duration 60s
          parallel: true
          fail-fast: false
          cloud-run-locally: false
          cloud-comment-on-pr: true
